version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: juego_backend
    ports:
      - "5000:5000"
    networks:
      - juego_net

  frontend:
    build:
      context: ./frontend
    container_name: juego_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - juego_net

networks:
  juego_net:
    driver: bridge
